"""creating tables

Revision ID: 4319e43d7b30
Revises: 
Create Date: 2023-04-24 07:41:22.962097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4319e43d7b30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('bookId')
    )
    op.create_index(op.f('ix_books_bookId'), 'books', ['bookId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_bookId'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
